アプリの設定画面作成
Sereno-Anan/SerenoAndroidApp pull request #82
Opened 2021-12-11 16:23 UTC by kinoshita0923

## Issueへのリンク

resolve: #78 

## やったこと

設定画面を作成した

## 変更内容

<img src="https://user-images.githubusercontent.com/84900789/145683745-d6992e16-ff17-4606-aba4-4e4771114e47.png" width=200px />

## やらないこと

なし

## できるようになること

### ユーザー目線
ウィジェットに表示されるデータの場所を設定できる

### 開発者目線
とくになし

## できなくなること（ユーザ・開発者 目線）

### ユーザー目線
なし

### 開発者目線
なし

## 動作確認

エミュレーターでビルドが通ったのを確認した

## その他

‘AndroidManifest.xml‘に新しい処理が追加された

## チェックリスト

- [x] タイトルをちゃんと設定できている
- [x] Assignerの設定ができている
- [x] Linked issuesの設定ができている
- [x] Milestoneの設定ができている
- [x] Projects(In Progress)が設定できている
- [x] Reviewerが設定できている

2021-12-11 21:54 UTC, nemuki requested changes
https://developer.android.com/guide/topics/appwidgets?hl=ja#Configuring

Configure Screenはこれです(ごめん)

これはこれでいいような気がするので一度置いておいて、もう一度mainからブランチ切り直してください〜

2021-12-11 21:54 UTC, nemuki commented on app/src/main/java/com/sereno/serenoandroidapp/activities/ConfigureActivity.kt
> +                        Toast.makeText(this, "This city name is not found", Toast.LENGTH_SHORT)
Snacbarにしてほしさある

2021-12-11 22:15 UTC, nemuki commented
このActivityをWidgetのConfigure Screenに回せそうならそれで対応しましょう~
Screenを開くときの記述ができるのであれば、SharedPreferenceに値があれば開かない的な感じにしてほしいです~

2021-12-12 11:01 UTC, kinoshita0923 commented
実現するのが厳しそうなので閉じます

2021-12-12 11:01 UTC, closed without merging